TRANSACTION_STATUS_PENDING = 'pending'
TRANSACTION_STATUS_COMPLETE = 'complete'
TRANSACTION_STATUS_REFUNDED = 'refunded'
TRANSACTION_STATUSES = (
    (TRANSACTION_STATUS_PENDING, TRANSACTION_STATUS_PENDING),
    (TRANSACTION_STATUS_COMPLETE, TRANSACTION_STATUS_COMPLETE),
    (TRANSACTION_STATUS_REFUNDED, TRANSACTION_STATUS_REFUNDED),
)
